feat: event change wheel
ostis-ai/sc-web pull request #102
Opened 2023-05-24 14:27 UTC by ChaikaS

2023-05-24 14:47 UTC, AlexandrZagorskiy approved these changes
Works well

2023-05-29 09:21 UTC, smousy approved these changes

2023-06-01 07:49 UTC, MikhailSadovsky requested changes

2023-06-01 07:49 UTC, MikhailSadovsky commented on components/scg/src/scg-render.js
> +                if(direction === 'up') self.scene.onMouseWheelUp(this, self);
```suggestion
                if (direction === 'up') self.scene.onMouseWheelUp(this, self);
```

2023-06-01 07:49 UTC, MikhailSadovsky commented on components/scg/src/scg-render.js
> +                if(direction === 'down') self.scene.onMouseWheelDown(this, self);
```suggestion
                if (direction === 'down') self.scene.onMouseWheelDown(this, self);
```

2023-06-01 08:41 UTC, MikhailSadovsky approved these changes

2023-06-01 08:42 UTC, merged