Fix/links identifier translation
ostis-ai/sc-web pull request #112
Opened 2023-06-08 14:23 UTC by MksmOrlov

![image](https://github.com/ostis-ai/sc-web/assets/36566977/f2fbd7aa-b149-4a37-ae63-4ce4443a8b2b)

2023-06-08 16:04 UTC, NikitaZotov commented on components/scg/src/scg-struct.js
> +                        if (link.text) {
Optimize count of if branches

2023-06-08 16:09 UTC, MikhailSadovsky requested changes

2023-06-09 12:15 UTC, MikhailSadovsky approved these changes

2023-06-09 14:22 UTC, NikitaZotov approved these changes

2023-06-09 14:24 UTC, merged