feat: auto-scale
ostis-ai/sc-web pull request #113
Opened 2023-06-12 10:51 UTC by ChaikaS

2023-06-12 20:36 UTC, smousy requested changes

2023-06-12 20:36 UTC, smousy commented on components/scg/kb/sources/controls/ui_scg_control_tool_autosize.scs
> +    *);;
add newline

2023-06-12 20:36 UTC, smousy commented on components/scg/src/scg-render.js
> +
remove

2023-06-12 20:36 UTC, smousy commented on components/scg/src/scg.js
> +            self.scene.render._changeContainerTransform([conteinerWidth * 0.3, conteinerHeight * 0.3], 0.5)
why 0.3 and 0.5, please use constants

2023-06-12 20:36 UTC, smousy commented on client/js/Core/componentsandbox.js
> +                const scgHeight = self.scene.render.d3_container[0][0].getBoundingClientRect().height + (conteinerHeight/2 + 350);
please use constants instead of numbers

2023-06-13 13:11 UTC, AlexandrZagorskiy approved these changes
Works well

2023-06-14 12:19 UTC, MikhailSadovsky requested changes

2023-06-14 12:19 UTC, MikhailSadovsky commented on client/static/components/css/bootstrap-override.css
> +.btn-group-vertical>.btn, .btn-group-vertical>.btn-group, .btn-group-vertical>.btn-group>.btn {
This file shouldn't be committed and should be added to gitignore

2023-06-14 12:19 UTC, MikhailSadovsky commented on client/js/Core/componentsandbox.js
> +        },300)
Please move to constant

2023-06-14 12:53 UTC, MikhailSadovsky approved these changes

2023-06-14 13:43 UTC, NikitaZotov commented on components/scg/kb/sources/controls/ui_scg_control_tool_autosize.scs
> +
Add newline

2023-06-14 13:47 UTC, NikitaZotov approved these changes

2023-06-14 13:48 UTC, merged