fix: add optional buttons to delete function
ostis-ai/sc-web pull request #119
Opened 2023-06-16 11:25 UTC by andrewKapustin22

2023-06-16 15:54 UTC, MikhailSadovsky requested changes

2023-06-16 15:54 UTC, MikhailSadovsky commented on scripts/secret.txt
> +LwRe/IK+TIyPANAUICfYpYoQ5sz7x0zdtxoxoY0J6oE=
Please don't commit this file

2023-06-16 15:54 UTC, MikhailSadovsky commented on components/scg/static/components/html/demo-scg-delete-panel.html
> +<div class="demo-fragments-window">
Please don't use 'demo' name

2023-06-16 15:54 UTC, MikhailSadovsky commented on client/static/components/html/demo-scg-delete-panel.html
> +<div class="demo-fragments-window">
Please don't commit this file, include in gitignore

2023-06-19 10:05 UTC, MksmOrlov commented on .gitignore
> +
add newline please

2023-06-19 10:24 UTC, MksmOrlov commented on components/scg/static/components/html/scg-delete-panel.html
And what about English mode? There is only Russian text

2023-06-22 19:42 UTC, MksmOrlov commented on .gitignore
> +
just remove space in the last line

2023-06-22 19:43 UTC, MksmOrlov approved these changes

2023-06-22 20:27 UTC, MikhailSadovsky requested changes

2023-06-22 20:27 UTC, MikhailSadovsky commented on client/js/Ui/core.js
> +            //   SCWeb.ui.DeleteScgButtons.init(),
Please don't leave commented code

2023-06-22 20:27 UTC, MikhailSadovsky commented on client/js/Ui/deleteScgButtons.js
> +            SCWeb.core.Server.resolveScAddr([expert_mode_identifier]).then(function (addrs) {
Please don't use `expert mode` words

2023-06-22 20:27 UTC, MikhailSadovsky commented on client/js/Ui/deleteScgButtons.js
> +SCWeb.ui.DeleteScgButtons = {
Is this file really needed?

2023-06-22 20:27 UTC, MikhailSadovsky commented on components/scg/src/deleteScgButtons.js
> +                var delete_from_wp = addrs[delete_from_working_place_button_identifier];
Please rename wp & dp to more clear names

2023-06-22 20:27 UTC, MikhailSadovsky commented on components/scg/src/deleteScgButtons.js
> +                if(delete_from_db) {
```suggestion
                if (delete_from_db) {
```

2023-06-22 20:27 UTC, MikhailSadovsky commented on components/scg/src/scg.js
> +                        // complete: function () {
Please remove unused code

2023-06-22 20:27 UTC, MikhailSadovsky commented on components/scg/src/scg.js
> +                                    // DeleteButtons.init(),
Please remove unused code

2023-06-22 20:27 UTC, MikhailSadovsky commented on components/scg/src/scg.js
> +                // if (self.scene.selected_objects.length > 1) {
Please remove unused code

2023-06-29 14:58 UTC, MikhailSadovsky commented on components/scg/src/scg.js
> +                if(!self.scene.selected_objects[0].sc_addr) {
Please fix **everywhere** in file
```suggestion
                if (!self.scene.selected_objects[0].sc_addr) {
```

2023-07-10 13:44 UTC, MikhailSadovsky approved these changes

2023-07-10 13:48 UTC, merged