fix: auto-scale
ostis-ai/sc-web pull request #125
Opened 2023-06-23 08:07 UTC by ChaikaS

2023-06-27 13:59 UTC, smousy approved these changes

2023-06-29 12:20 UTC, MikhailSadovsky requested changes

2023-06-29 12:20 UTC, MikhailSadovsky commented on components/scg/src/scg.js
> +            if(currentRectTop < 0 && currentRectLeft < 0) {
```suggestion
            if (currentRectTop < 0 && currentRectLeft < 0) {
```

2023-06-29 12:21 UTC, MikhailSadovsky commented
SCg view inside SCn not working properly
![image](https://github.com/ostis-ai/sc-web/assets/8840551/ff2b4e91-3207-41da-ba76-c96f3573d523)

2023-07-02 16:14 UTC, MikhailSadovsky approved these changes

2023-07-04 08:07 UTC, merged