fix: install script with specification
ostis-ai/sc-web pull request #163
Opened 2024-02-02 19:40 UTC by MakarenkoAI

2024-02-02 19:48 UTC, MksmOrlov requested changes

2024-02-02 19:48 UTC, MksmOrlov commented on specification.scs
> -    => nrel_installation_script: [/scripts/install_deps_ubuntu.sh](* <- lang_en;; *);
remove lang_en in script formalization

2024-02-02 19:48 UTC, MksmOrlov commented on scripts/install.sh
> +echo -e "${BLUE}Installation\v${NC}"
can we use `stage` instead of echo?

2024-02-02 19:48 UTC, MksmOrlov commented on scripts/install.sh
> +pip3 install -r "${CURRENT_DIR}/../requirements.txt" && npm install
install_deps_ubuntu already execute this

2024-02-02 19:55 UTC, MakarenkoAI commented on scripts/install.sh
> +echo -e "${BLUE}Installation\v${NC}"
no

2024-02-05 13:36 UTC, MksmOrlov requested changes

2024-02-05 13:36 UTC, MksmOrlov commented on specification.scs
> +    => nrel_component_address: [https://github.com/MakarenkoAI/sc-web] (* <- concept_github_url;; *);
```suggestion
    => nrel_component_address: [https://github.com/ostis-ai/sc-web] (* <- concept_github_url;; *);
```

2024-02-05 13:36 UTC, MksmOrlov commented on scripts/install.sh
> +"${CURRENT_DIR}/install_deps_ubuntu.sh"
```suggestion
"${CURRENT_DIR}/install_dependencies.sh"
```

2024-02-05 13:36 UTC, MksmOrlov commented on scripts/install.sh
> +stage "Installation"
```suggestion
stage "Install depemdencies"
```

2024-02-05 13:36 UTC, MksmOrlov commented on scripts/install.sh
> +
stage "sc-web installed successfully"

2024-02-05 19:11 UTC, MksmOrlov approved these changes

2024-02-06 08:11 UTC, NikitaZotov approved these changes

2024-02-07 14:22 UTC, merged