docs: write docs on new scn
ostis-ai/sc-web pull request #21
Opened 2022-09-12 07:39 UTC by NikitaZotov

2022-09-12 09:46 UTC, VasKho requested changes
We don't have following commands in `scn-latex-plugin`
```TeX
\scnexplanation
\scnnote
\begin{scnsubdividing} % i.e. environment
```
If you're really would like to use you should define this commands in main file or simply replace them with `\scnrelfrom{пояснение}`, `\scnrelfrom{примечание}`, `\begin{scnrelfromset}{разбиение}` respectively.

2022-09-12 09:46 UTC, VasKho commented on docs/sc_web.tex
> +\scnrelfrom{иллюстрация}{\scnfileimage{images/sc_web_new_arch}}
```suggestion
\scnrelfrom{иллюстрация}{\scnfileimage{images/sc\_web\_new\_arch}}
```

2022-09-21 14:18 UTC, VasKho requested changes

2022-09-26 08:50 UTC, VasKho commented on docs/sc_web.tex
> +    Кроме того, часть интерфейса фактически работает напрямую с sc-памятью с использованием технологии WebSocket, а часть -- через прослойку на базе библиотеки tornado для языка программирования Pyth
```suggestion
    Кроме того, часть интерфейса фактически работает напрямую с sc-памятью с использованием технологии WebSocket, а часть -- через прослойку на базе библиотеки tornado для языка программирования Python, что приводит к дополнительным зависимостям от сторонних библиотек.}
```

2022-09-26 08:50 UTC, VasKho commented on docs/sc_web.tex
> +    \scnfileitem{Не реализован механизм наследования при добавлении новых внешних языков. Например, добавление нового языка даже очень близкого к SCg-коду требует физического копирования кода компоне
```suggestion
    \scnfileitem{Не реализован механизм наследования при добавлении новых внешних языков. Например, добавление нового языка даже очень близкого к SCg-коду требует физического копирования кода компонента и внесение соответствующих изменений, при этом получаются два никак не связанных между собой компонента, которые начинают развиваться независимо друг от друга.}
```

2022-09-26 09:04 UTC, VasKho approved these changes

2022-09-26 09:37 UTC, KovalM approved these changes

2022-09-26 09:39 UTC, merged