Add double click logic in scg view
ostis-ai/sc-web pull request #61
Opened 2023-01-18 08:42 UTC by smousy

2023-01-20 17:06 UTC, KovalM requested changes
1. Try checkout to SCg and checkout to SCn. You will get constantly loading
2. Try checkout to SCg, do double click to any node, checkout to SCn. You will get lang checkout

2023-01-23 18:49 UTC, KovalM approved these changes

2023-01-24 09:50 UTC, MikhailSadovsky requested changes

2023-01-24 09:50 UTC, MikhailSadovsky commented on client/js/Ui/windowmanager.js
> +        if(!command_state.format)
```suggestion
        if (!command_state.format)
```

2023-01-24 09:50 UTC, MikhailSadovsky commented on client/js/Ui/windowmanager.js
> +        if(!command_state.lang)
```suggestion
        if (!command_state.lang)
```

2023-01-24 11:49 UTC, MikhailSadovsky approved these changes

2023-01-24 15:48 UTC, NikitaZotov commented on client/js/Core/main.js
>       * @param {Array} cmd_args Array of sc-addrs with command arguments
Add info about this feature into changelog, please

2023-01-25 09:16 UTC, NikitaZotov approved these changes

2023-01-25 11:07 UTC, merged