fix: add wait time for command getting answer
ostis-ai/sc-web pull request #67
Opened 2023-02-08 21:13 UTC by smousy

2023-02-14 11:22 UTC, smousy commented
фикс логики ожидания ответа, раньше мы бы поискали один раз и все, а ответ создался немножко позже, теперь в течении некоторого времени мы ищем ответ

2023-02-28 15:53 UTC, KovalM requested changes
Update source project after merge this PR

2023-02-28 15:53 UTC, KovalM commented on server/handlers/api_logic.py
> +        wait_time += wait_dt
This fix will do search request answer_wait_timeout/0.01 times for no answer cases. We should make this code depend on time, not on the number of requests.

2023-03-02 08:20 UTC, KovalM requested changes

2023-03-02 08:20 UTC, KovalM commented on server/handlers/api_logic.py
> +        while (((begin_time + tornado.options.options.answer_wait_timeout) > time.time()) & waiting):
Move to single thread

2023-03-13 07:33 UTC, KovalM requested changes

2023-03-13 07:33 UTC, KovalM commented on server/handlers/api_logic.py
> +        print(result)
Remove prints

2023-03-13 07:33 UTC, KovalM commented on server/handlers/api_logic.py
> +        result = _get_answer()
Revert using time.sleep() because without it we will spam server

2023-03-22 08:11 UTC, KovalM approved these changes

2023-03-22 08:11 UTC, KovalM commented on server/handlers/api_logic.py
> +    print('finish result: ', result)
Remove

2023-03-23 10:37 UTC, MikhailSadovsky approved these changes

2023-03-26 21:29 UTC, merged