Add condition for NaN situation
ostis-ai/sc-web pull request #70
Opened 2023-02-08 21:21 UTC by smousy

2023-02-13 16:54 UTC, smousy commented
Добавление проверок на NaN ситуации для SCg ("базовый порядок разделов" в SCg висло после частичной загрузки)

2023-02-28 16:29 UTC, KovalM requested changes

2023-02-28 16:29 UTC, KovalM commented on client/static/common/d3/d3.js
> +        return attrNull;
```suggestion
        return name.local ? attrNullNS : attrNull;
```

2023-02-28 16:29 UTC, KovalM commented on client/static/common/d3/d3.js
> +        return attrFunction;
```suggestion
     return name.local ? attrFunctionNS : attrFunction;
```

2023-02-28 16:29 UTC, KovalM commented on client/static/common/d3/d3.js
> +      value = dNaNPoint;
This function didn't change its params before. Looks like we should return function like in other case

2023-03-13 07:30 UTC, KovalM approved these changes

2023-03-13 09:42 UTC, MikhailSadovsky approved these changes

2023-03-14 09:57 UTC, merged