[fix] Save page after reload
ostis-ai/sc-web pull request #73
Opened 2023-02-13 15:20 UTC by smousy

2023-02-13 15:29 UTC, KovalM approved these changes

2023-03-13 09:41 UTC, MikhailSadovsky requested changes

2023-03-13 09:41 UTC, MikhailSadovsky commented on client/js/Core/main.js
> +                setCookie('last_page_cmd_addr',cmd_addr);
Please move` 'last_page_cmd_addr'` and `'last_page_cmd_args'` to constant vars

2023-03-13 09:41 UTC, MikhailSadovsky commented on client/js/Core/main.js
> +                    if(last_page_cmd_addr && last_page_cmd_args && Number(last_page_cmd_args[0]) !== cmd_args[0]){
```suggestion
                    if (last_page_cmd_addr && last_page_cmd_args && Number(last_page_cmd_args[0]) !== cmd_args[0]){
```

2023-03-26 21:24 UTC, merged