feat: add editing links
ostis-ai/sc-web pull request #82
Opened 2023-03-21 17:53 UTC by nastatsan

2023-03-22 21:43 UTC, smousy requested changes

2023-03-22 21:43 UTC, smousy commented on client/js/Utils/sc_helper.js
> +ScHelper.prototype.templateCheckSystIdtf = async (link) => {
Is this function using anywhere?

2023-03-22 21:43 UTC, smousy commented on components/scg/src/scg.js
> +        // if (this.canEdit) {
please, delete comments

2023-03-22 21:43 UTC, smousy commented on components/scg/src/scg.js
> +            // if (this.scene.selected_objects.length > 0) this.showTool(this.toolDelete());
please delete comments

2023-03-22 21:44 UTC, smousy reviewed
please format changed files

2023-03-23 09:13 UTC, nastatsan commented on components/scg/static/components/html/scg-tools-panel.html
> +        <label id="scg-tool-set-content" type='button' class="btn btn-default sc-no-default-cmd btn-xs" sc_control_sys_idtf="ui_scg_control_tool_set_content"
yes

2023-03-23 12:15 UTC, KovalM requested changes

2023-03-28 08:27 UTC, KovalM approved these changes

2023-03-28 10:04 UTC, smousy approved these changes

2023-03-28 10:43 UTC, AlexandrZagorskiy reviewed
update changelog

2023-03-28 10:46 UTC, MikhailSadovsky commented on components/scg/src/scg.js
> +        this.hideTool(this.toolDelete());
Here you changed existing delete logic. Delete button will be never shown, is this expected behavior?

2023-03-28 11:45 UTC, MikhailSadovsky commented on components/scg/src/scg.js
>              if (this.scene.selected_objects.length > 0) this.showTool(this.toolDelete());
This condition should go on level up. We can select multiple objects with Ctrl and delete button should be available as exist

2023-03-28 12:20 UTC, AlexandrZagorskiy approved these changes
Don't forget to rebase, conflict in changelog

2023-03-28 12:22 UTC, MikhailSadovsky commented on docs/changelog.md
> +- Add editing links with saving them
```suggestion
- Add ability to edit links and save changes
```

2023-03-28 12:25 UTC, MikhailSadovsky approved these changes

2023-03-28 12:32 UTC, merged