Add specification
ostis-ai/sc-web pull request #87
Opened 2023-04-05 16:25 UTC by SHtress

Add .scs file with specification for component manager.
Need to update:
- Purpose
- Explanation
- Authors

2023-04-05 16:27 UTC, SHtress commented on specification.scs
> +    => nrel_install_scripts: [cd scripts && ./install.sh](* <- lang_en;; *);
I think there shouldn't be English language. Probably there should be script language?

2023-04-10 11:14 UTC, MksmOrlov requested changes

2023-04-10 11:14 UTC, MksmOrlov commented on specification.scs
> +    => nrel_sc_identifier: [SC-web specification](* <- lang_en;; *);
It is not SC-web specification. It is SC-web itself

2023-04-10 11:14 UTC, MksmOrlov commented on specification.scs
> +    => nrel_key_sc_element: concept_animal;
hmm I am not sure

2023-04-10 11:14 UTC, MksmOrlov commented on specification.scs
> +    => nrel_install_scripts: [cd scripts && ./install.sh](* <- lang_en;; *);
Make only one script

2023-04-10 11:38 UTC, smousy requested changes

2023-04-10 11:38 UTC, smousy commented on specification.scs
> +    => nrel_install_scripts: [cd scripts && ./install.sh](* <- lang_en;; *);
It is changed for nrel_installation_script

2023-04-10 12:23 UTC, MksmOrlov commented on specification.scs
> +    => nrel_authors: ... (* <- empty_set *);
You can find some information for the specification from @NikitaZotov soft platform monography section

2023-04-10 20:52 UTC, smousy approved these changes

2023-04-11 15:40 UTC, MksmOrlov requested changes
Check unresolved

2023-04-11 15:46 UTC, SHtress commented on specification.scs
> +    => nrel_authors: ... (* <- empty_set *);
Yes, there is some information but it is useless for component manager right now.

2023-04-11 15:47 UTC, SHtress commented on specification.scs
> +    => nrel_install_scripts: [cd scripts && ./install.sh](* <- lang_en;; *);
Well, if you insist.

2023-04-11 15:50 UTC, MksmOrlov requested changes

2023-04-11 15:50 UTC, MksmOrlov commented on specification.scs
> +    => nrel_installation_script: [cd scripts && ./install_deps_ubuntu.sh && ./install.sh](* <- lang_en;; *);
remove lang_en

2023-04-11 15:50 UTC, MksmOrlov commented on specification.scs
> +    => nrel_authors: ... (* <- empty_set *);
remove authors relation or specify it as not empty

2023-04-11 15:52 UTC, MksmOrlov approved these changes

2023-04-11 15:55 UTC, merged